### ISSUE TITLE
bug: Browser compatibility issues

### ISSUE THREAD

**Issue by Wennndy716** [WKU-SRA/WKU-SRA-Website#5]
**Describe the bug**
The homepage title does not display correctly when viewed on the WeChat browser. Instead of showing the intended title, it defaults to a generic or incorrect title.

**To Reproduce**
1. Open WeChat and click the website link 
2. Observe that the title in the main tag displayed on the browser is not the expected one.

**Expected behavior**
The homepage title should display correctly as specified in the HTML title tag, regardless of the browser being used.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macos 14.5
 - Browser: Wechat default browser 
 - Version no version are provided

**Comment by AlbertZhaoCA** [comment]
Hi Wennndy,

Thank you for letting me know the issue, I find it is regarding the text background clip. 

### How the issue arises

The problem arises because WeChat browsers require vendor prefixes for the `background-clip` property. because it use  `-webkit-` engine to render such css.


### My Solution

I add `@supports` rule in global css.

```css
@supports (-webkit-background-clip: text) or (background-clip: text) {
  .fallback-text-color {
    background: linear-gradient(to bottom, #fcfcfc, #39414d); 
    -webkit-background-clip: text;
    background-clip: text;
    color: transparent; 
  }
}
```

This ensures that the gradient text effect will work in WeChat browsers.

However, a better choice is to use `PostCSS` in the project. Doing this will make your life easier 😝 

Happy hacking,
Albert
